### ISSUE TITLE
Refined Soundex and Jaro

### ISSUE THREAD

**Issue by DonaldTsang** [jamesturk/jellyfish#103]
These could be directly ported into Jellyfish as these are C files
- [ ] Refined Soundex
Refined soundex source: https://github.com/Rostepher/libstrcmp/blob/master/src/phonetic/refined_soundex.c  
Original soundex source: https://github.com/Rostepher/libstrcmp/blob/master/src/phonetic/soundex.c  
Comparing with CJellyfish: https://github.com/jamesturk/cjellyfish/blob/master/soundex.c

- [ ] Original Jaro
Jaro and Jaro-Winker source: https://github.com/Rostepher/libstrcmp/blob/master/src/distance/jaro_winkler.c
Comparing to CJellyfish: https://github.com/jamesturk/cjellyfish/blob/master/jaro.c

- [ ] Basic SIFT
SIFT original (no CJellyfish reference): https://github.com/jhermsmeier/sift.c
JS example: https://github.com/timoxley/sift

**Comment by DonaldTsang** [comment]
If possible, include other forms of SIFT,
- SIFT https://siderite.blogspot.com/2006/11/fast-string-distance-sift-algorithm.html
- SIFT2 https://siderite.blogspot.com/2007/01/super-fast-string-distance-algorithm.html
- SIFT3 https://siderite.blogspot.com/2007/04/super-fast-and-accurate-string-distance.html
- SIFT4 https://siderite.blogspot.com/2014/11/super-fast-and-accurate-string-distance.html

**Comment by jamesturk** [comment]
i'm open to PRs if there's a need to, but I don't think there's a clear reason to switch to any of these implementations- at least jaro is almost identical to what we started w/
