### ISSUE TITLE
jellyfish 0.6.1 is not working on python 3.6

### ISSUE THREAD

**Issue by GuruMahesh4444** [jamesturk/jellyfish#105]
I have python3.6 in my windows pc. i am not able to import jellyfish and i am getting below error. 
 
import jellyfish.
jellyfish.levenshtein_distance(u'jellyfish', u'smellyfish')

Error:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-24c8f9837225> in <module>()
----> 1 import jellyfish
      2 jellyfish.levenshtein_distance(u'jellyfish', u'smellyfish')

ModuleNotFoundError: No module named 'jellyfish'

**Comment by jamesturk** [comment]
can you print the output of pip freeze?

**Comment by GuruMahesh4444** [comment]
C:\WINDOWS\system32>pip freeze
certifi==2018.4.16
chardet==3.0.4
idna==2.7
requests==2.19.1
urllib3==1.23

**Comment by jamesturk** [comment]
it doesn't look like you have the library installed, try pip install
jellyfish

**Comment by GuruMahesh4444** [comment]
C:\Users\Gayathri>pip install jellyfish
Collecting jellyfish
Installing collected packages: jellyfish
Successfully installed jellyfish-0.6.1

C:\Users\Gayathri>pip freeze
certifi==2018.4.16
chardet==3.0.4
idna==2.7
jellyfish==0.6.1
numpy==1.14.5
pandas==0.23.1
python-dateutil==2.7.3
pytz==2018.5
requests==2.19.1
six==1.11.0
urllib3==1.23


![image](https://user-images.githubusercontent.com/30309249/42231930-930511d8-7f0a-11e8-963b-4dd6e4a04108.png)

**Comment by jamesturk** [comment]
Your Jupyter installation is using a different virtualenv, as evidenced by
the fact that you aren't seeing Jellyfish & Jupyter show up in the same pip
freeze.  I'd recommend reading up a bit on how to manage these
environments, sorry but I won't be able to assist here as this isn't a
jellyfish issue

**Comment by GuruMahesh4444** [comment]
Thank you for your support i found that problem and resolved
