### ISSUE TITLE
Expose variables of Jaro-Winkler as function arguments

### ISSUE THREAD

**Issue by RedAero** [jamesturk/jellyfish#106]
It would be very useful and fairly simple to give users the possibility of overwriting the weights and maximum match length used by the Winkler algorithm for the user to modify. Specifically I am talking about the values "i" and "0.1" in 

`weight += i * 0.1 * (1.0 - weight)`

"i" is, as per the original Winkler definition, capped at 4, and 0.1 is an arbitrary weight that is recommended to be 0.1 but is not mandatory. For longer strings and use cases outside of names of people it's quite useful to be able to modify these values so that the algorithm is more or less sensitive to strings matching at their beginning. The possibility of making 0.1 a function of the string length is also interesting.

(As a sidenote, the python-Levenshtein package works this way)

**Comment by jamesturk** [comment]
I'd be very glad to accept a PR w/ this if you have time
