### ISSUE TITLE
Any plans on providing wheels?

### ISSUE THREAD

**Issue by jezeniel** [jamesturk/jellyfish#107]
Is it possible to provide wheels based on https://github.com/pypa/manylinux , it will be easier to install this package inside docker images?

EDIT: forked this repo and created wheels using `manylinux`, https://github.com/jezeniel/jellyfish-wheel
will deprecate my fork once this is resolved.

**Comment by jamesturk** [comment]
I'd be very glad to accept a PR if you have time

**Comment by jezeniel** [comment]
Hi @jamesturk what will be the flow of the build? If I integrate manylinux build in travis, who will release the wheels?

**Comment by jezeniel** [comment]
@jamesturk do you prefer a simple shell script or i can create a very simple Makefile, and are you also okay with adding Docker in your workflow?

**Comment by jamesturk** [comment]
a Makefile for this would be fine with me- and yes Docker for this portion
seems like it'd be needed

**Comment by jamesturk** [comment]
added experimental wheels in latest release!
