### ISSUE TITLE
NYSIIS rule for names starting in PF not implemented

### ISSUE THREAD

**Issue by ahood** [jamesturk/jellyfish#114]
According to the NYSIIS algorithm, PFEISTER should get mapped to FASTAR. But jellyfish.nysiis('PFEISTER') outputs PFASTAR. Issue fixed and this test case added in https://github.com/jamesturk/jellyfish/pull/113.

**Comment by ahood** [comment]
I know the fixes are now reflected in the master branches of the testdata and cjellyfish submodules. When do you think the updated version of jellyfish that reflects these changes will be available via pip/Pypi?

**Comment by jamesturk** [comment]
this is now available in 0.7.0
