### ISSUE TITLE
Pip doesn't install the cjellyfish

### ISSUE THREAD

**Issue by bhargav0795** [jamesturk/jellyfish#119]
Installed jellyfish through PIP, but somehow pip doesn't install the cjellyfish. I had to do it manually by installing through ".tar.gz". 

python version - 3.7.1 
Pip version - 19.0.3
Windows version - Windows 10 Pro

**Files when I install jellyfish through ".tar.gz"**
![1](https://user-images.githubusercontent.com/25449723/53961956-e19f0a00-40b7-11e9-84d3-c5d10e7f78a1.PNG)

**Files when I install jellyfish through pip**
![2](https://user-images.githubusercontent.com/25449723/53962116-3e022980-40b8-11e9-8632-e9fa8de1bc58.PNG)

**Comment by danigamba** [comment]
Having the same issue, Jellyfish 0.7.2 installed from pip doesn't build the cython implementation.

**Comment by jamesturk** [comment]
what OS?

**Comment by danigamba** [comment]
Ubuntu 18.04 64bit
pip 19.1.1
Python 3.6.7

**Comment by jamesturk** [comment]
do you have python3-dev installed? can you paste the output from the
installation?
