### ISSUE TITLE
Issue in match_rating_codex() output

### ISSUE THREAD

**Issue by AidanFray** [jamesturk/jellyfish#121]
`match_rating_codex` does not seem to be removing double constants pairs correctly and, therefore, is producing an incorrect codex.

The result from:

```python
from jellyfish import match_rating_codex

print(match_rating_codex("William"))
```

Produces:
```
WLLM
```

This is not correct and the result should `WLM` due to the double constant pair being removed.

This is stated in the Wikipedia article linked in the Jellyfish documentation:
```
[...]
2. Remove the second consonant of any double consonants present
[...]
```

**Comment by jamesturk** [comment]
fixed in 0.8
