### ISSUE TITLE
PHP metaphone and JS metaphone match but NOT Jellyfish

### ISSUE THREAD

**Issue by ojnc** [jamesturk/jellyfish#123]
acceptingness metahone PHP & JS agree as AKSPTNKNS
But jellyfish returns KSPTNKNS leading A is dropped

**PHP Metaphone is built-in**
<?php
echo metaphone('michael')."\n";
echo metaphone('crevalle')."\n";
echo metaphone('Filipowitz')."\n";
echo metaphone('Xavier')."\n";
echo metaphone('delicious')."\n";
**echo metaphone('acceptingness')."\n";**
echo metaphone('allegrettos')."\n";
?>
OUTPUT of metaphone('acceptingness') is AKSPTNKNS

_[https://www.npmjs.com/package/metaphone](https://www.npmjs.com/package/metaphone)_
var metaphone = require('metaphone')
metaphone('michael')
metaphone('crevalle')
metaphone('Filipowitz')
metaphone('Xavier')
metaphone('delicious')
**metaphone('acceptingness')**
metaphone('allegrettos')
OUTPUT of metaphone('acceptingness') is AKSPTNKNS

**jellyfish as installed using pip**
from jellyfish import metaphone
metaphone('michael')
metaphone('crevalle')
metaphone('Filipowitz')
metaphone('Xavier')
metaphone('delicious')
**metaphone('acceptingness')**
metaphone('allegrettos')

OUTPUT of metaphone('acceptingness') is possibly wrong?
returns KSPTNKNS 
**leading A is dropped**

**Comment by jamesturk** [comment]
fixed in upcoming 0.8
