### ISSUE TITLE
jellyfish.soundex yields DeprecationWarning PY_SSIZE_T_CLEAN in python 3.8

### ISSUE THREAD

**Issue by motin** [jamesturk/jellyfish#125]
jellyfish.soundex in python 3.8 yields `DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats`

Just a warning so far, but will require a change in future python versions.

**Comment by Tenzer** [comment]
Same for `jellyfish.levenshtein_distance`, taken from example in README:
```python
Python 3.8.1 (default, Jan  7 2020, 10:39:14)
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jellyfish
>>> jellyfish.levenshtein_distance(u'jellyfish', u'smellyfish')
<stdin>:1: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
2
```

**Comment by Tenzer** [comment]
I had a stab at fixing this in https://github.com/jamesturk/cjellyfish/pull/7.

**Comment by henrist** [comment]
@jamesturk This was fixed in https://github.com/jamesturk/cjellyfish but the submodule of this repo is still poining to the old version, so it is not fixed for the jellyfish package yet.

Any timeline for a new release including the changes in https://github.com/jamesturk/cjellyfish/pull/7 ?

**Comment by jamesturk** [comment]
Thanks for the ping on this, just pulled the update into the repo.  I'll
look at a new release as soon as I have a bit of time.
