### ISSUE TITLE
Publish in conda-forge

### ISSUE THREAD

**Issue by blabalme** [jamesturk/jellyfish#129]
Conda forge feedstock has been archived : https://github.com/conda-forge/jellyfish-feedstock

Is it possible to maintain lastest versions in conda-forge ?

**Comment by jamesturk** [comment]
Sorry, I'm not clear what conda-forge is.  The package is published to PyPI
though- I think all standard tools can pull from there.

**Comment by blabalme** [comment]
I use conda because it checks dependencies, it is not possible to install pypi packages with conda.

**Comment by jamesturk** [comment]
Sorry, but that sounds like a conda issue, as an open source maintainer I don't have the resources to support non-standard package indexes.

**Comment by blabalme** [comment]
I understand that you don't have time to do it, but conda it's standard package indexes.

Example : https://www.anaconda.com/
