### ISSUE TITLE
PyArg_ParseTuple("u#") is deprecated

### ISSUE THREAD

**Issue by methane** [jamesturk/jellyfish#131]
https://docs.python.org/3/c-api/arg.html#strings-and-buffers

> Deprecated since version 3.3, will be removed in version 4.0: Part of the old-style Py_UNICODE API; please migrate to using PyUnicode_AsWideCharString().

Please use 'U' and PyUnicode_AsWideCharString instead.

**Comment by nijel** [comment]
In Python 3.10 this produces:

> DeprecationWarning: getargs: The 'u' format is deprecated. Use 'U' instead.
