### ISSUE TITLE
do next release via GitHub actions

### ISSUE THREAD

**Issue by jamesturk** [jamesturk/jellyfish#138]
a reminder to myself that I'd like to use the new feature added in #135 for pushing a release :)

**Comment by ofek** [comment]
any idea when the next release might be?

**Comment by jamesturk** [comment]
Not sure, could find time soon as needed.  Are there bug fixes/features/etc. that aren't released yet that you're looking for?

**Comment by ofek** [comment]
No, just need wheels for Windows & macOS

**Comment by jamesturk** [comment]
giving it a shot now

**Comment by jamesturk** [comment]
getting an error, it seems related to the point raised in #136 about the linux wheels

**Comment by jamesturk** [comment]
https://github.com/jamesturk/jellyfish/runs/2089228575?check_suite_focus=true
