### ISSUE TITLE
Unable to install C Implementation of Jellyfish in Linux

### ISSUE THREAD

**Issue by mirbaquari** [jamesturk/jellyfish#140]
Dear Creators,

I am new to using python jellyfish module. When I install the module, only python implementation of jellyfish gets installed but I need C implementation.

Can you please help me to install C implementation of jellyfish

**Comment by jamesturk** [comment]
Hi, do you have a specific error?

**Comment by mirbaquari** [comment]
No specific error, I installed the module using pip and it only installs python implementation not c.

**Comment by jamesturk** [comment]
Sorry, without any details I won't be able to help.  I'd recommend checking into your build environment for your system (do you have a C compiler? etc.) as I'd imagine that is the source of the error but without a log there's not much I can say.
