### ISSUE TITLE
Cannot untilize C extensions on x86 Linux platform when installed through pip

### ISSUE THREAD

**Issue by leonright** [jamesturk/jellyfish#145]
Starting from version `0.8.4` of `jellyfish`, a universal wheel for all platforms has been published. At the same time, there is no wheel for x86 Linux platforms.

This results in `pip` preferring the universal wheel over source installation (see the warning note in the `Pure Python` section on the `wheels` [web-page](https://pythonwheels.com/)), thus the pure Python implementation without the C extensions is always installed.

Our project requires high precision when computing string distances, so we would appreciate if this issue would be resolved so we could use latest versions of the library

Thank you for your time

**Comment by jamesturk** [comment]
thanks for the heads up, i'll release a fix w/o a universal wheel while we wait to figure out how to get the manylinux wheels working better

**Comment by jamesturk** [comment]
let me know if 0.8.8 (which should be fully uploaded in ~5 mins) fixes the issue

**Comment by leonright** [comment]
Thank you for the quick response 🙇 

Yes, `0.8.8` worked for us. Thanks for dealing with it
