### ISSUE TITLE
Crashes in recent releases

### ISSUE THREAD

**Issue by nijel** [jamesturk/jellyfish#146]
Recent releases starting with 0.8.4 cause Weblate testsuite to crash. To me, it seems there is something wrong in the binary wheel for cjellyfish, but I didn't yet find time investigate that deeper.

The crash on GitHub actions:

```
/home/runner/work/_temp/988f1f7c-01c9-46c4-8bc3-1ea4098717f7.sh: line 1:  8872 Killed                  coverage run ./manage.py test
Error: Process completed with exit code 137.
```

For example, it can be seen here: https://github.com/WeblateOrg/weblate/runs/3343181381?check_suite_focus=true

Looking at the diff https://github.com/jamesturk/jellyfish/compare/v0.8.3...v0.8.4, I don't see anything obvious what could cause such problems...

**Comment by jamesturk** [comment]
Without more context there isn't much we can do, if you can provide us with a failing test, etc. please re-open
