### ISSUE TITLE
Jaro-Winkler similarity calculation changed between 0.8.8 and 0.8.9

### ISSUE THREAD

**Issue by leonright** [jamesturk/jellyfish#150]
`jellyfish.jaro_winkler_similarity()` returns different numbers in `0.8.9` compared to `0.8.8` on Python 3.9.5 with C distribution installed.

Verified on both on Windows 10 and on CentOS 7.

```python
# 0.8.8
>>> import jellyfish
>>> jellyfish.jaro_winkler_similarity("123X", "123Y")
<<< 0.8333333333333334

# 0.8.9
>>> import jellyfish
>>> jellyfish.jaro_winkler_similarity("123X", "123Y")
<<< 0.8833333333333334
```

Could you please look into the issue or let us know the reason for this change in results received?

Thank you

**Comment by jamesturk** [comment]
see #147
