### ISSUE TITLE
Match Rating comparison doesn't give any output (missing value)

### ISSUE THREAD

**Issue by ammubharatram** [jamesturk/jellyfish#155]
Reproducible example:

`print(match_rating_codex("MARIE HELENE"))`

Output:  MRHLN

`print(match_rating_codex("MARIA RIO"))`
Output:  MR

When I run match rating comparison, it doesn't give any output:

`match_rating_comparison('MARIE HELENE','MARIA RIO')`

However if I remove the word 'Helene' in the first name, I get boolean output. Can't understand when it gives missing value and when not. For my dataset of 7000 names, it gave 4 missing values. Any idea why?

Other trials to reproduce:

`match_rating_comparison('MARIE RELENE','MARIA RIO')`

Output: True
It seems like H at the beginning seems the problem by multiple trials. Seems like a bug with H to me. Any thoughts on this? Thanks in advance!

**Comment by jamesturk** [comment]
just added a test case for this, will try to take a look when I get a chance, if someone else wants to get to it first the problem is likely in cjellyfish/mra.c
