### ISSUE TITLE
py310 jellyfish.metaphone incorrectly raises TypeError with string argument

### ISSUE THREAD

**Issue by jbrockmendel** [jamesturk/jellyfish#160]
I get this on both Mac and Ubuntu in python 3.10.4, not in 3.8 or 3.9
```
>>> import jellyfish
>>> jellyfish.metaphone("Alabama")
<stdin>:1: DeprecationWarning: getargs: The 'u' format is deprecated. Use 'U' instead.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: str argument expected
```

**Comment by NickCrews** [comment]
Pretty sure this is caused by

https://github.com/jamesturk/cjellyfish/blob/66c48ae2998af3364b0653f74634b507fa5be823/jellyfishmodule.c#L262-L272

but I am not familiar enough with the [c arg parsing API](https://docs.python.org/3/c-api/arg.html) to know what exactly the fix is. If someone knows what to do, I can actually implement it.

**Comment by jamesturk** [comment]
@jbrockmendel What version of Jellyfish are you using?  As you can see in the code NickCrews linked the code has been updated to use "U" instead of "u"

**Comment by jbrockmendel** [comment]
With jellyfish 0.6.1 (Mac, py3.9.13) I just got

```
>>> import jellyfish
>>> jellyfish.metaphone("Alabama")
<stdin>:1: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
'ALBM'
```

**Comment by jamesturk** [comment]
0.6.1? 

On Mon, Sep 12, 2022, at 3:03 PM, jbrockmendel wrote:
> 
> 
> With jellyfish 0.6.1 (Mac, py3.9.13) I just got
> 
> `>>> import jellyfish
> >>> jellyfish.metaphone("Alabama")
> <stdin>:1: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
> 'ALBM'
`

**Comment by jbrockmendel** [comment]
> 0.6.1?

Yes.  No warning when I upgrade to 0.9.0.  Though pip complains that `us` is pinned to 0.6.1.

Fine by me to close here.
