### ISSUE TITLE
no-name-in-module pylint

### ISSUE THREAD

**Issue by vitalie-cracan** [jamesturk/jellyfish#192]
from jellyfish import jaro_winkler_similarity

generates this complaint from pylint: 

E0611: No name 'jaro_winkler_similarity' in module 'jellyfish' (no-name-in-module)

**Comment by jamesturk** [comment]
Can you give any more details on environment/etc?

**Comment by jamesturk** [comment]
Ah so this only occurs via `pylint`, I'd consider checking with them, it's not a tool I use.
