### ISSUE TITLE
cp312 built distributions are missing for Windows, macOS, and musllinux

### ISSUE THREAD

**Issue by remyjette** [jamesturk/jellyfish#197]
Since jellyfish requires a rust toolchain to build from a source distribution, installation is challenging on Windows macOS and musllinux without a built distribution.

The cp312 built distributions are available on PyPI for manylinux, but other platforms are missing.

**Comment by jamesturk** [comment]
Thanks for the nudge on this. Just pushed a new CI config & will push out a release now.

Update: Hitting a strange error trying to build right now, I'll need revisit later

**Comment by pwbriggs** [comment]
@jamesturk Any update on this? I did some experimentation myself and I can't figure out that error either.

**Comment by jamesturk** [comment]
Not beyond a bit of checking which uncovered the fact it it specific to running the Python 3.12 stuff on GH actions.  I put it aside hoping it'd resolve itself, but I think I need to try to reproduce in a smaller repo and/or open a support ticket.

**Comment by Chuck321123** [comment]
I had the same problem when trying to install Spyder with python 3.12 as Spyder requires jellyfish. However, a guy mentioned that by installing jellyfish version 0.7.1 (with pip) the installation worked, which it also worked for me. Use this information @jamesturk if its helpful.

**Comment by jamesturk** [comment]
This is now resolved, please let me know if you encounter any issues with `1.0.3`

**Comment by pwbriggs** [comment]
Nice work, @jamesturk, thanks! It works for me!

I'm curious now, though. What was that CI error about?

**Comment by jamesturk** [comment]
It was a tiny issue with the `venv` script, https://github.com/python/cpython/issues/112252
