### ISSUE TITLE
jaro_distance missing?

### ISSUE THREAD

**Issue by yi0n** [jamesturk/jellyfish#198]
Hi,

it seems the jellyfish.jaro_distance() function isn't available anymore.
I didn't found any information about that in the changelog.
Official site and docs still displays the function in the example code.

Has this to do with #122 ?

**Comment by PatrickKudo** [comment]
Yes, it appears it was changed to jaro_similarity() as of `jellyfish==1.0`. See [https://jamesturk.github.io/jellyfish/functions/](url)

`jellyfish.jaro_similarity("New","Now")`

**Comment by jamesturk** [comment]
Thanks for pointing out the old README/docs.  I'll update that for the next release once the Python 3.12 issue is resolved.
