### ISSUE TITLE
Error in jellyfish due to some special characters

### ISSUE THREAD

**Issue by joumaico** [jamesturk/jellyfish#200]
The error is caused by a special single quotation mark (`’`) in the code. The error message is as follows:

```rust
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```

To reproduce the issue, you can run the following code:

```python
import jellyfish

str1 = "i’m going home"
str2 = "i go home"

print(jellyfish.match_rating_comparison(str1, str2))
```

**Resolution:**

Ensure that the library correctly handles character encoding and escaping to support a wide range of characters and special symbols, including but not limited to the special single quotation mark (`’`). The library should process these characters without causing exceptions.

**Comment by jamesturk** [comment]
Thanks for this report, adding a test and taking a look now.
