### ISSUE TITLE
No module named 'jellyfish._rustyfish'

### ISSUE THREAD

**Issue by MarcosAnim** [jamesturk/jellyfish#201]
When i try to import jellyfish, the terminal come up with the error.
my python version : 3.9.13

`import jellyfish`

Traceback (most recent call last):
  File "c:\Users\Lenovo\Desktop\Code\Easylayout - Delly's\Selo code.py", line 1, in <module>
    import jellyfish
  File "C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\jellyfish\__init__.py", line 3, in <module>
    from ._rustyfish import *
ModuleNotFoundError: No module named 'jellyfish._rustyfish'

**Comment by jamesturk** [comment]
Hi,

To help here I’d need more information— can you go into details about how you installed it, what OS and version of relevant tools you used, what messages appear during installation, etc.

**Comment by kb-amitsingh** [comment]
Runtime.ImportModuleError: Unable to import module 'main': No module named 'jellyfish._rustyfish'

Python 3.9.18
jellyfish 1.0.1
Mac M1 


@jamesturk

**Comment by jamesturk** [comment]
@kb-amitsingh same question as I had above,  More details would be helpful.  Most importantly, how did you install it?

**Comment by kb-amitsingh** [comment]
> @kb-amitsingh same question as I had above, More details would be helpful. Most importantly, how did you install it?

It's working fine locally. But getting the issue on lambda deployment even though I have added the Python dependencies also.
It works fine while deploying lambda by docker.

@kb-amitsingh

**Comment by jamesturk** [comment]
That sounds like a lambda limitation if it can be installed in other ways.  Going to close this issue for now for lack of actionable information/suspected environment issues.  If someone can provide steps to reproduce on their local machine I'll gladly investigate.

**Comment by gnevan** [comment]
Hi @jamesturk,

Some similar issue here. I have installed jellyfish 1.0.4 with pip on Python 3.8 (Windows 7 SP1). 
```
C:\Python38>pip install jellyfish
Collecting jellyfish
  Obtaining dependency information for jellyfish from https://files.pythonhosted.org/packages/9a/37/b723defd1b9d60122b1df204b00268b1c563a26e0170eba8bd9c3b0ee3f8/jellyfish-1.0.4-cp38-none-win_amd64.whl.me
  Downloading jellyfish-1.0.4-cp38-none-win_amd64.whl.metadata (2.6 kB)
Downloading jellyfish-1.0.4-cp38-none-win_amd64.whl (206 kB)
   ---------------------------------------- 206.5/206.5 kB 331.0 kB/s eta 0:00:00
Installing collected packages: jellyfish
Successfully installed jellyfish-1.0.4
```
But when I do 
```
import jellyfish
```
This error appears (jupyter):
```
ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_15192/276106370.py in <module>
----> 1 import jellyfish

c:\python38\lib\site-packages\jellyfish\__init__.py in <module>
      1 import warnings
      2 
----> 3 from ._rustyfish import *
      4 from . import _jellyfish

ImportError: DLL load failed while importing _rustyfish: The specified procedure could not be found.
```
Or this for python:
```
C:\Python38>python.exe
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import jellyfish
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python38\lib\site-packages\jellyfish\__init__.py", line 3, in <module>
    from ._rustyfish import *
ImportError: DLL load failed while importing _rustyfish: The specified procedure could not be found.
```
What is a _rustyfish? What DLL does it need?

**Comment by jamesturk** [comment]
I imagine this is a Windows 7 issue, Windows 7 has been EOL for 4 years, I have no idea what the status of Python is on that system.  Python 3.8 is EOL this year as well, if you can replicate on anything newer let me know, otherwise I'm not sure what this means or how to help unfortunately.

On Sun, Jun 9, 2024, at 3:44 PM, gnevan wrote:
> 
> 
> Hi @jamesturk <https://github.com/jamesturk>,
> 
> Some similar issue here. I have installed jellyfish 1.0.4 with pip on Python 3.8 (Windows 7 SP1).
> 
> `C:\Python38>pip install jellyfish
> Collecting jellyfish
>   Obtaining dependency information for jellyfish from https://files.pythonhosted.org/packages/9a/37/b723defd1b9d60122b1df204b00268b1c563a26e0170eba8bd9c3b0ee3f8/jellyfish-1.0.4-cp38-none-win_amd64.whl.me
>   Downloading jellyfish-1.0.4-cp38-none-win_amd64.whl.metadata (2.6 kB)
> Downloading jellyfish-1.0.4-cp38-none-win_amd64.whl (206 kB)
>    ---------------------------------------- 206.5/206.5 kB 331.0 kB/s eta 0:00:00
> Installing collected packages: jellyfish
> Successfully installed jellyfish-1.0.4
`
> But when I do
> 
> `import jellyfish
`
> This error appears (jupyter):
> 
> `ImportError                               Traceback (most recent call last)
> ~\AppData\Local\Temp/ipykernel_15192/276106370.py in <module>
> ----> 1 import jellyfish
> 
> c:\python38\lib\site-packages\jellyfish\__init__.py in <module>
>       1 import warnings
>       2 
> ----> 3 from ._rustyfish import *
>       4 from . import _jellyfish
> 
> ImportError: DLL load failed while importing _rustyfish: The specified procedure could not be found.
`
> Or this for python:
> 
> `C:\Python38>python.exe
> Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import jellyfish
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Python38\lib\site-packages\jellyfish\__init__.py", line 3, in <module>
>     from ._rustyfish import *
> ImportError: DLL load failed while importing _rustyfish: The specified procedure could not be found.
`
