### ISSUE TITLE
cp311 and cp312 built distributions for Alpine Linux

### ISSUE THREAD

**Issue by hockeygoalie35** [jamesturk/jellyfish#209]
Hi! Similar to #197 , would it be possible to release a built distro for Alpine Linux? I can successfully install 0.10 from source, but any version after doesn't have a compatible wheel, and building from source yields:

![image](https://github.com/jamesturk/jellyfish/assets/7758029/1b8b3d5f-1f0f-443b-b8c7-7ac15eaef0f2)

I'm on ARM64 if that makes any difference.

**Comment by jamesturk** [comment]
Alpine uses musl and we do build wheels for this: https://pypi.org/project/jellyfish/#files but doing some searching it seems wheels are a common problem on Alpine.  If there is a specific config change that you know of that'd help here I'm glad to make it, but this feels like it may be an Alpine issue more than a PyPI thing.

**Comment by hockeygoalie35** [comment]
Hmm...strange. I'll investigate a bit more and see what I can do. Please keep this open for a little bit if that's ok. I'll come back with any solution I can find.

**Comment by maxbachmann** [comment]
As far as I can see you didn't build + upload wheels for musl arch64, but only for manylinux arch64.

**Comment by jamesturk** [comment]
added for 1.0.4
