### ISSUE TITLE
Wrap Rust rphonetic library functions

### ISSUE THREAD

**Issue by mcarans** [jamesturk/jellyfish#213]
The Rust [rphonetic](https://github.com/Dalvany/rphonetic) library has a few more phonetic functions like refined soundex and double metaphone. Could jellyfish wrap those functions (or even use all the functions from that library)?

**Comment by jamesturk** [comment]
for now, I'd suggest someone that wants to use that library to use it directly.  I'd be open to looking at it at some point in the future though.
