### ISSUE TITLE
 Install fails to build on Python 3.13

### ISSUE THREAD

**Issue by Arcturuss** [jamesturk/jellyfish#217]
Basically same as #199 

Python 3.13.0 just released, and there is no prebuilt packages for it, I guess.

**Comment by energynumbers** [comment]
Any progress on this? Is there a way to build for windows yet, for python 3.13?

**Comment by jamesturk** [comment]
No, I don't have access to a Windows system to test so sort of at the whim of GitHub Actions.

**Comment by energynumbers** [comment]
ok, I've never used rust or maturin before, but I'll give it a go

**Comment by energynumbers** [comment]
ok, it said:
 Finished `dev` profile [unoptimized + debuginfo] target(s) in 1m 03s                              
 📦 Built wheel for CPython 3.13 to D:\zaps\jellyfish\target\wheels\jellyfish-1.1.0-cp313-cp313-win_amd64.whl
 
 Wheel then installs ok on python 3.13
 
 First time success. Built on windows 10, python 3.13.
 
 That's good, right? Should I be trying some profile other than dev?

**Comment by energynumbers** [comment]
[dropbox link to compiled wheel](https://www.dropbox.com/scl/fi/k2ohw3ht9obpxy2h9uxj8/jellyfish-1.1.0-cp313-cp313-win_amd64.whl?rlkey=dfp1s7lvegarx7f4w79g3x5oj&dl=0)

**Comment by energynumbers** [comment]
So, the release profile built ok too, once I realised I just needed to run `maturin build -r`! Maybe it was because I was compiling using python 3.13, maybe because it was a very clean new install of both rust and maturin, but there were no warnings or hiccups.

**Comment by jamesturk** [comment]
thanks for this, release was pushed!

**Comment by tswast** [comment]
I'm only seeing Windows 3.9 support for the compiled builds on the [files for 1.1.2](https://pypi.org/project/jellyfish/1.1.2/#files), which is the most recent release.

**Comment by energynumbers** [comment]
@jamesturk that is odd  - I'm seeing the same as tswast - the windows py-3.13 build goes fine, but it doesn't get uploaded to pypi.org upon release. I've never uploaded to pypi, so I don't know what's going on here, but it seems a strange thing, and it means that lots of users still won't be able to use jellyfish on python 3.13 on windows.

**Comment by energynumbers** [comment]
ok, I think this should fix it https://github.com/jamesturk/jellyfish/pull/223
