### ISSUE TITLE
[1.1.2] PyPI page missing wheels for most versions of Python on Windows

### ISSUE THREAD

**Issue by MatthewMarinets** [jamesturk/jellyfish#222]
Had a user bump into an issue related to this earlier today getting into a project that used jellyfish as a dependency. Doing a pip install, he was getting an error like:
```
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]
```

Checking out the PyPI page, it seems that wheel downloads only exist for Python 3.9, and are missing for all other Python versions.

The user got around this issue by installing cargo so he could build locally. Playing around with a venv, I found that I wasn't running into this issue as our requirement was for `jellyfish>=1.1.0` and 1.1.0 downloads don't have this issue (downloads support 3.8~3.12 on windows), and I had installed it earlier and thus didn't need to update locally.

While asking around, someone on our discord also mentioned github messing around with build artifacts recently, but I don't have more information myself. It's possible that this issue came from github actions doing something weird, though.

Is it possible to update the wheels on PyPI to support other versions of Python on windows?

Edit: Adding a link to the PyPI files page to quickly check if things have changed: https://pypi.org/project/jellyfish/#files
ctrl+F for "windows" should highlight all the windows wheels. As of 2024-12-09, the only windows one is CPython 3.9 Windows x86_64

**Comment by jamesturk** [comment]
For now on Windows stick to 1.1.1, 1.1.2 was released to try to debug the Windows release process which seems to be broken on GitHub Actions. There's no actual code difference.

**Comment by eendebakpt** [comment]
@jamesturk Using version 1.1.1 indeed works. But many packages using jellyfish as a dependency will now fail during installation and inexperienced users might have a hard time figuring out what to do.

An option (maybe for next time) is to release the debugging package as a pre-release version. That would allow you to test the release process, but the pre-release is not selected by pip (unless the user specifically specifies so).

![image](https://github.com/user-attachments/assets/bf63251f-fc61-4072-b674-f6e29f6b32de)

**Comment by jamesturk** [comment]
1.1.3 fixes this issue
