### ISSUE TITLE
jaro_winkler() takes no keyword arguments 

### ISSUE THREAD

**Issue by primoz-k** [jamesturk/jellyfish#44]
`jellyfish.jaro_winkler(unicode_str1, unicode_str2, long_tolerance=True)` returns Error:
`TypeError: jaro_winkler() takes no keyword arguments`.

Am I doing something wrong, because `long_tolerance` seems like it should be valid keyword argument in this implementation:
`def jaro_winkler(s1, s2, long_tolerance=False):...`

**Comment by jamesturk** [comment]
Thanks. on the road but will look into this soon. which Python interpreter?

**Comment by primoz-k** [comment]
It's 2.7.6. Thank you for your response.

**Comment by jamesturk** [comment]
this is fixed in 0.5.1!  thanks for the report
