### ISSUE TITLE
TypeError: expected unicode, got str

### ISSUE THREAD

**Issue by kyleiwaniec** [jamesturk/jellyfish#45]
I am getting this error when running any of the functions in the readme:

```
>>> import jellyfish
>>> jellyfish.metaphone('Jellyfish')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: expected unicode, got str
```
I am not sure if this is an error in jellyfish or a more general python error
I have tried with python 2.6 and 2.7

Is there something I can do to fix it?

**Comment by kyleiwaniec** [comment]
this works, but it's kinda weird..

`jellyfish.jaro_distance(unicode('jellyfish'),unicode('smellyfish'))`

**Comment by crdunwel** [comment]
@kyleiwaniec Python 3 `str` type is equivalent to Python 2 `unicode` type. See http://lucumr.pocoo.org/2014/1/5/unicode-in-2-and-3/ . Try `jellyfish.metaphone(u'Jellyfish')` .

**Comment by kyleiwaniec** [comment]
ah, cool. thank you :)
