### ISSUE TITLE
metaphone differences between PyPy and CPython

### ISSUE THREAD

**Issue by jcarbaugh** [jamesturk/jellyfish#46]
jellyfish returns different metaphone encodings when used on PyPy and CPython. Issue was discovered in python-us (https://github.com/unitedstates/python-us/issues/13) and reproduced below:

Python 3.5.1:
```
>>> jellyfish.metaphone('Utah')
'UT'
```

Python 2.7.11:
```
>>> jellyfish.metaphone(u'Utah')
'UT'
```

PyPy 4.0.1:
```
>>>> jellyfish.metaphone(u'Utah')
u'UTH'
```

**Comment by jcarbaugh** [comment]
There's a bug in the Python implementation of metaphone. #47 should be a fix, assuming I'm reading the rules for H correctly.

**Comment by jamesturk** [comment]
thanks for this & the quick patch, I'll find some time to get a bugfix release out soon
