### ISSUE TITLE
Please include docs/ and testdata/ in PyPi's tar.gz

### ISSUE THREAD

**Issue by viccuad** [jamesturk/jellyfish#48]
Hi, 

~~I'm packaging jellyfish for Debian (in fact it is already done)~~
(there's another person already doing it), and
it would be nice if the PyPi tar.gzs shipped with the docs included
(primarly because of the changelog).

Cheers and thanks

**Comment by jamesturk** [comment]
Hi- I'd be fine w/ PRs to do this, are you just talking the rst or built docs?

**Comment by viccuad** [comment]
From the Debian side of view, the .rst would suffice, and one can build
the html docs automatically with Sphinx with them.

My python-fu is not relative new, but by reading
https://docs.python.org/2/distutils/sourcedist.html#manifest-related-options
seems that the solution is to include the missing files to the `MANIFEST.in` file.

I have included the `docs/` and `testdata/` dirs, which are valuable for anyone
trying to build the package.

I have tested it succesfully and uploaded the result to [testPyPI](https://wiki.python.org/moin/TestPyPI):

https://testpypi.python.org/pypi/jellyfish

Let me know what do you think about this :)

**Comment by viccuad** [comment]
mmh, the solution I just proposed leaves a `testdata/.git` in the sdist tarball.

We can either make a fine grade `MANIFEST`, or drop it and use `package_data`
or `data_files`as explained in
https://docs.python.org/2/distutils/sourcedist.html#specifying-the-files-to-distribute

I guess that's your call :)

**Comment by viccuad** [comment]
fixed the PR adding a `global-exclude .git` that seems like the simplest solution and future-proof.
