### ISSUE TITLE
Python 2 examples on README.rst

### ISSUE THREAD

**Issue by diego-plan9** [jamesturk/jellyfish#51]
A small issue noticed during the [Debian packaging](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=807432#70) process: it seems that the README [*"Example Usage"*](https://github.com/jamesturk/jellyfish/blob/master/README.rst#example-usage) section contains some examples that, if executed directly, result in a minor error when using the Python 2 version:

```python
>>> import jellyfish
>>> jellyfish.levenshtein_distance('jellyfish', 'smellyfish')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "jellyfish/_jellyfish.py", line 13, in levenshtein_distance
raise TypeError(_no_bytes_err)
TypeError: expected unicode, got str

>>> jellyfish.levenshtein_distance(u'jellyfish', u'smellyfish')
2
```

It seems that this by design - if that is the case, I'm wondering if the `README.rst` file should be updated to reflect the right usage of the arguments (always forcing the user to use `unicode` instead of `str`)?

**Comment by jamesturk** [comment]
Ah good point, I'd be fine adding the u prefix in the README for clarity for people still using Python 2

**Comment by jamesturk** [comment]
just fixed this in the latest README

**Comment by diego-plan9** [comment]
Thanks for the quick turnaround and for updating the README, cool!
