### ISSUE TITLE
String processing error with phonetic encoding functions

### ISSUE THREAD

**Issue by dirkbike** [jamesturk/jellyfish#53]
When passing a string to `metaphone()` or `soundex()`, Python 3.4 throws `TypeError: expected str, got bytes`.  This does not occur with `nysiis()`.

**Comment by jamesturk** [comment]
hmm nysiis(b'test') throws the error (as expected) for me, can you send a test case where NYSIIS doesn't reject bytes?

**Comment by dirkbike** [comment]
Here are all three cases.  I am not using any string prefixes.  The results are the same using the unicode `u` prefix and all three fail as expected when using the bytes `b` prefix.
```
>>> jellyfish.metaphone('test')
Traceback (most recent call last):
  File "<pyshell#123>", line 1, in <module>
    jellyfish.metaphone('test')
TypeError: expected str, got bytes
>>> jellyfish.soundex('test')
Traceback (most recent call last):
  File "<pyshell#124>", line 1, in <module>
    jellyfish.soundex('test')
TypeError: expected str, got bytes
>>> jellyfish.nysiis('test')
'TAST'
```

**Comment by dirkbike** [comment]
Any ideas why this is happening?

**Comment by jamesturk** [comment]
I'll find some time soon to look at it but I'd just make sure you're always
passing strings.

**Comment by dirkbike** [comment]
Yes, I am passing strings, and by default all strings in Python 3 are Unicode.  I am also running on Windows 7 in case the issue is related to how the modules are compiled for Windows.  Let me know if you'd like me to test anything.

**Comment by jamesturk** [comment]
Hmm that's a good thought, I can't seem to reproduce this, there's a good chance this is related to Windows.

What does type('test') return on this system?

**Comment by dirkbike** [comment]
```
>>> type('test')
<class 'str'>
```

**Comment by jamesturk** [comment]
OK I think I found the cause, thanks for bringing this to my attention.
I'll try to figure out a fix ASAP

**Comment by jamesturk** [comment]
Can you try the latest git version to see if it fixes your issue?

**Comment by dirkbike** [comment]
Confirmed!  Thanks

**Comment by dirkbike** [comment]
Out of curiosity, do you know why the issue only appeared on Windows?

**Comment by jamesturk** [comment]
That I have no clue about unfortunately. All I know is that there's a lot
of weird behavior when it comes to C API string processing between
different Python versions so I'm chalking it up to that. The fix is almost
surely a better way to do it anyway, most functions had been moved to
grabbing "u#" out of the tuple but for some reason I'd left those two since
it didn't seem necessary.  Now it's consistent everywhere.

**Comment by jamesturk** [comment]
I'll get a 0.5.6 out soon
