### ISSUE TITLE
Similarity functions for damerau_levenshtein, levenshtein and hamming

### ISSUE THREAD

**Issue by J535D165** [jamesturk/jellyfish#60]
Hello Jamesturk,

What are your thoughts about adding similarity functions for damerau_levenshtein, levenshtein and hamming? Currently, only distance functions are available for these algorithms. I think, most of the applications use similarity functions.

What about:
damerau_levenshtein_similarity
levenshtein_similarity 
hamming_similarity

Comparable with the R-package https://github.com/markvanderloo/stringdist. 

I can make the Python ones if you like. C version does not look that hard either. 

Kind regards, Jonathan

**Comment by jamesturk** [comment]
Is there an explanation somewhere of how those similarities are
used/calculated?    I'm not super familiar w/ R but it looks like they're
doing (score / max_score)?



On Mon, Sep 12, 2016 at 4:51 PM, Jonathan de Bruin <notifications@github.com

**Comment by jamesturk** [comment]
going to close this out, feel free to reopen if there's still interest/progress
