### ISSUE TITLE
Docs for contributors: How to build Jellyfish and run tests

### ISSUE THREAD

**Issue by nchammas** [jamesturk/jellyfish#64]
Are there basic docs anywhere on how to build Jellyfish and run tests? Common practice is to put info like this either directly in the README or in a separate CONTRIBUTING file.

The intended audience for such docs would be current and potential contributors who want to do The Right Thing™ before contributing code. They don't have to be long--a short paragraph will suffice if the process is not complicated.

**Comment by jamesturk** [comment]
you can simply run tox to test :)

**Comment by nchammas** [comment]
So, to setup a development environment for Jellyfish, all you need to do is clone the repo and run this?

```sh
pip install tox
tox
```

Would you like me to add a note about this to the README, or do you think it's fine as-is? (I've never used tox before, so it wasn't obvious to me. Perhaps most Python developers will get this without any help, though.)

**Comment by jamesturk** [comment]
Hm, wouldn't hurt to add to the README.  It is fairly common but always
good to be explicit
