### ISSUE TITLE
Implement property-based tests to ensure both the Python and C implementations are correct and in sync

### ISSUE THREAD

**Issue by nchammas** [jamesturk/jellyfish#68]
It seems that Jellyfish has a number of problems related to Unicode (#55, #56, #63), as well as other issues that result in the Python and C implementations of the same algorithms returning different results (#65).

[Having 100% code coverage](https://coveralls.io/github/jamesturk/jellyfish) doesn't seem to be enough to catch these kinds of problems, and writing up unit tests to cover all the possible corner cases sounds like a big burden to take on.

Thankfully, a project like Jellyfish seems like a great fit for [property-based testing](https://www.youtube.com/watch?v=zi0rHwfiX1Q).

Using a property-based testing library like [Hypothesis](http://hypothesis.works/), we can specify rules like "The Python and C implementations of `soundex()` must always return the same output." and Hypothesis will generate thousands of test strings for us and check that the rule holds, regardless of input.

For example, using Hypothesis, I quickly dug up two problems with `soundex()`, one of which I reported in #65. I also found a seg fault in the C implementation of `match_rating_comparison()` (#73). I think if we instrument property-based tests for all the algorithms in Jellyfish, we'll be able to dig up many bugs like this and ensure a higher level of quality without needing to manually write dozens of unit tests.

If this sounds promising to you, I would be happy to submit a PR implementing property-based tests for all of Jellyfish's algorithms. The new tests will likely dig up many issues, so it would probably be best if we used the open PR to drive bug fixes in master, merging it in only after the uncovered bugs have all been addressed. That way we benefit from the new tests without suddenly breaking the build.

**Comment by nchammas** [comment]
@jamesturk - Does this sound interesting to you?

**Comment by jamesturk** [comment]
Sorry for missing this last time, this definitely sounds interesting.
Thanks!

**Comment by jamesturk** [comment]
Doing away with split implementations, #68
