### ISSUE TITLE
cjellyfish.match_rating_comparison('', '') seg faults

### ISSUE THREAD

**Issue by nchammas** [jamesturk/jellyfish#73]
Repro:

```python
>>> import jellyfish.cjellyfish as cjellyfish
>>> cjellyfish.match_rating_comparison('', '')
Segmentation fault: 11
```

Found with [Hypothesis](http://hypothesis.works). (PR forthcoming for #68.)

**Comment by J535D165** [comment]
This issue has the label 'ready'. Is this correct and if so, when is the fix pushed?

**Comment by jamesturk** [comment]
sorry, that is an automatic label set by waffle.io- I don't think there's a patch yet
