### ISSUE TITLE
Similar type of strings give error - IndexError: string index out of range

### ISSUE THREAD

**Issue by YashSharma** [jamesturk/jellyfish#87]
jellyfish.jaro_winkler('aaaa','aaaaa')

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-216-3987eab40141> in <module>()
----> 1 jellyfish.jaro_winkler('aaaa','aaaaa')

C:\Users\ys16219\AppData\Local\Continuum\Anaconda2\lib\site-packages\jellyfish\_jellyfish.pyc in jaro_winkler(s1, s2, long_tolerance)
    117 
    118 def jaro_winkler(s1, s2, long_tolerance=False):
--> 119     return _jaro_winkler(s1, s2, long_tolerance, True)
    120 
    121 

C:\Users\ys16219\AppData\Local\Continuum\Anaconda2\lib\site-packages\jellyfish\_jellyfish.pyc in _jaro_winkler(ying, yang, long_tolerance, winklerize)
     89         j = max(min_len, 4)
     90         i = 0
---> 91         while i < j and ying[i] == yang[i] and ying[i]:
     92             i += 1
     93         if i:

IndexError: string index out of range

**Comment by jamesturk** [comment]
old version, added a test case though to ensure we don't have a regression
