### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by fpessolano** [jamesturk/jellyfish#89]
How can i install it for use in python3?
Thanks

**Comment by jamesturk** [comment]
can you clarify what you mean?  the project works w/ Python 3 out of the box

**Comment by fpessolano** [comment]
How do I install it then? I am porting all my code form python2 and I am fiding difficult to install it with pip/pip3

**Comment by jamesturk** [comment]
do you have any specific errors? I'm afraid I may have to close this otherwise

**Comment by fpessolano** [comment]
my fault, it works I was trying to instal wrongly. sorry
