### ISSUE TITLE
handling umlauts

### ISSUE THREAD

**Issue by geoHeil** [jamesturk/jellyfish#90]
`jellyfish.match_rating_codex('ä')`fails with

`ValueError: character U+ffffffff is not in range [U+0000; U+10ffff]`

how should umlauts be handled to be fit for jellyfish?

**Comment by jamesturk** [comment]
if you import from jellyfish._jellyfish you'll get the Python version that handles unicode properly

**Comment by maxbachmann** [comment]
@jamesturk is this still an issue? as far as I can see this is fixed:
```python
>>> jellyfish._jellyfish.match_rating_codex('ä')
'Ä'
>>> jellyfish.cjellyfish.match_rating_codex('ä')
'Ä'
```

**Comment by jpt-c** [comment]
thanks for pointing this out

**Comment by jamesturk** [comment]
added a test to confirm this is fixed & avoid regression
