### ISSUE TITLE
Double Metaphone support

### ISSUE THREAD

**Issue by maxharlow** [jamesturk/jellyfish#91]
Would be great to have support for the more advanced [Double Metaphone](https://en.wikipedia.org/wiki/Metaphone#Double_Metaphone) algorithm in Jellyfish.

**Comment by gwerbin** [comment]
FWIW Aspell published their implementation [here](http://aspell.net/metaphone/dmetaph.cpp) (linked from [this page](http://aspell.net/metaphone/). It seems to use a lot of C++ features, though, so a rewrite might be a lot of work. Not sure how complicated it would be to use as a library, and link Cjellyfish to it.

**Comment by gwerbin** [comment]
There's already a double metaphone implementation here: https://github.com/dedupeio/doublemetaphone

**Comment by jamesturk** [comment]
nice find, I'd definitely point people to that if they need double metaphone.  going to close this
