### ISSUE TITLE
Adding QWERTY support to DL distance

### ISSUE THREAD

**Issue by DocShahrukh** [jamesturk/jellyfish#92]
Adjusting cost in DL distance for QWERTY keypad mistakes, may be to others too.
Please see if you're free.

`key_pairs = [{'q','a'},{'q','w'},{'w','a'},{'w','e'},{'w','s'},{'e','s'},{'e','d'},{'e','r'},{'r','d'},{'r','f'},{'r','t'},{'t','g'},{'t','y'},{'y','g'},{'y','h'},{'y','u'},{'u','h'},{'u','j'},{'u','i'},{'i','j'},{'i','k'},{'i','o'},{'o','k'},{'o','l'},{'o','p'},{'l','k'},{'m','k'},{'m','n'},{'n','j'},{'n','b'},{'b','h'},{'b','v'},{'v','g'},{'v','c'},{'c','f'},{'c','x'},{'x','d'},{'x','z'},{'z','s'}]`

`def damerau_levenshtein_cost(a,b):
    if a==b :
        return 0
    elif set([a,b]) in key_pairs:
        return .25
    return 1`

`            cost = damerau_levenshtein_cost(s1[i-1],s2[j-1])
`

I wish this hack finds some stack

**Comment by jsfenfen** [comment]
This is really interesting. @DocShahrukh would this approach work for OCR errors too, assuming one came up with a useful weighting? So '1' paired with 'l', etc.

**Comment by jamesturk** [comment]
I think it’d make sense to make the cost function configurable, that’d let
people do this for different layouts or ocr specific functions. I’d be glad
to incorporate such a PR if anyone has time

**Comment by DonaldTsang** [comment]
Don't forget QWERTZ (Germany, Austria and Eastern Europe)!

**Comment by DimitriPapadopoulos** [comment]
And [AZERTY](https://en.wikipedia.org/wiki/AZERTY), [Dvorak](https://en.wikipedia.org/wiki/Dvorak_keyboard_layout), and [other layouts](https://en.wikipedia.org/wiki/Keyboard_layout). Cost function really needs to be configurable, perhaps with a few standard costs.

> This is really interesting. @DocShahrukh would this approach work for OCR errors too, assuming one came up with a useful weighting? So '1' paired with 'l', etc.

Indeed, see for example:
* [What are the common OCR errors with capitals?](https://stackoverflow.com/questions/8284111/what-are-the-common-ocr-errors-with-capitals#8284176)
* [Deep Statistical Analysis of OCR Errors for Effective Post-OCR Processing](https://zenodo.org/record/3245169/files/JCDL2019_Deep_Analysis.pdf)
