### ISSUE TITLE
Jellyfish 6.0.0 doesn't import _cjellyfish

### ISSUE THREAD

**Issue by zhou9110** [jamesturk/jellyfish#96]
Hi, I currently have a problem with Jellyfish 6.0.0. 

When I type ```import jellyfish; jellyfish.library``` in the Python console, it returns ```Python```. It seems likes cjellyfish is not imported.

After swtiching to jellyfish 5.6.0, it can import the C codes successfully.
And I have found that the same problem occurred in two computers (Windows 10 64 bits and OS X 11.12), 

I think this may imply that something wrong with Jellyfish 6.0.0, and want to report this issue just in case.

**Comment by jamesturk** [comment]
can you give some details on your installation?  do you get errors during the pip install?

**Comment by zhou9110** [comment]
Hi james,

Sorry for the late reply. i have met some unicode decode errors when installing Jellyfish and other libraries, but after upgraded to pip 10.0.0 the installation works fine.


Below is the detail of the installation.
``` Shell
PS C:\Users\zhou9> python -m pip install jellyfish
Collecting jellyfish
  Using cached jellyfish-0.6.0-py3-none-any.whl
Installing collected packages: jellyfish
Successfully installed jellyfish-0.6.0
You are using pip version 9.0.3, however version 10.0.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

PS C:\Users\zhou9> python
```
```Python
Python 3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:27:37) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import jellyfish
>>> jellyfish.library
'Python'
>>>
```

**Comment by mode-13** [comment]
Hi James,

I'm seeing the same thing on Ubuntu 16.04.  Same pip output, same library value, and reverting to 5.6 gets me back onto C.

Let me know if there is any other information I can provide that would help.

**Comment by mode-13** [comment]
That did the trick.  Back on C again with 0.6.1.  Thanks for the quick fix.
