### ISSUE TITLE
Price-matching rockymadden's stringmetric

### ISSUE THREAD

**Issue by DonaldTsang** [jamesturk/jellyfish#97]
* Phonetic Algorithm
    - Double Metaphone (Queued phonetic metric and algorithm)
    - NYSIIS (Phonetic metric and algorithm)
    - Refined NYSIIS (Phonetic metric and algorithm)
    - Refined Soundex (Phonetic metric and algorithm)
    - Soundex (Phonetic metric and algorithm)

* Similarity Metrics
    - Dice / Sorensen (Similarity metric)
    - Jaccard (Similarity metric)
    - Monge-Elkan (Queued similarity metric)
    - Needleman-Wunch (Queued similarity metric)
    - N-Gram (Similarity metric)
    - Overlap (Similarity metric)
    - Ratcliff-Obershelp (Similarity metric)
    - Tanimoto (Queued similarity metric)
    - Tversky (Queued similarity metric)
    - Smith-Waterman (Queued similarity metric)
    - Weighted Levenshtein (Similarity metric)

Link: https://github.com/rockymadden/stringmetric
Most edited branch: https://github.com/halfmatthalfcat/stringmetric

**Comment by jamesturk** [comment]
I'm open to submissions of various algorithms but I'm going to close this issue as too broad.  Feel free to submit PRs if you'd like to add any of these

**Comment by DonaldTsang** [comment]
Also see Elixir https://github.com/smashedtoatoms/the_fuzz

**Comment by DonaldTsang** [comment]
For more choices in Java: https://github.com/tdebatty/java-string-similarity  
For more choices in C#: https://github.com/feature23/StringSimilarity.NET
For more choices in C: https://github.com/rieck/harry
https://github.com/StefH/SimMetrics.Net/tree/master/src/SimMetrics.Net/Metric

**Comment by DonaldTsang** [comment]
https://github.com/wolfpaulus/phonetic-alg-compare

**Comment by DonaldTsang** [comment]
Python: https://github.com/ronggong/phoneticSimilarity
C#: https://github.com/jalle007/WordComparision

**Comment by DonaldTsang** [comment]
If possible, include other forms of SIFT,
- SIFT https://siderite.blogspot.com/2006/11/fast-string-distance-sift-algorithm.html
- SIFT2 https://siderite.blogspot.com/2007/01/super-fast-string-distance-algorithm.html
- SIFT3 https://siderite.blogspot.com/2007/04/super-fast-and-accurate-string-distance.html
- SIFT4 https://siderite.blogspot.com/2014/11/super-fast-and-accurate-string-distance.html
