### ISSUE TITLE
RFC: drop Python 2 support in 0.7.0

### ISSUE THREAD

**Issue by jamesturk** [jamesturk/jellyfish#98]
I intend for the next major release of Jellyfish to drop Python 2 support- if this would cause a major hardship for anyone that is watching, please comment here.   Simplifying the code, especially the C portions, would be a big win & with Python 2.x deprecating looming it seems like the time might be upon us

**Comment by J535D165** [comment]
Whoops. Missed this one. My library https://github.com/J535D165/recordlinkage relies heavily on jellyfish. I will do a quick fix. 

I do have a remark. There is no information/warning/error on installing the library with Python 2. This is confusing. 

Another remark. The strings in the README do have a `u` in front of it. We can remove these, isn't it?

**Comment by jamesturk** [comment]
Yes those u" can go--

I'll take a look at the options, I believe there's now a way to make sure
Py2 users get 0.6 and Py3 users can get newer versions.

 is recordlinkage python 2/3?

**Comment by J535D165** [comment]
Yes it is 2/3. 

It would be nice if py2 user get 0.6.x by default. I'm not sure how his works.

**Comment by jamesturk** [comment]
I just withdrew 0.7 and pushed 0.7.1 which should (at least on modern
versions of pip/setuptools) respect the python_requires variable.
This means users on Python 2 will get 0.6.1 and everyone else gets the
latest.  It's new to me so let me know if you have any issues with it
